# Generated by Django 5.1.15 on 2026-10-05 10:51

import accounts.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_options_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='JPG, PNG or WebP, up to 5 MB.', null=True, upload_to=accounts.images.profile_upload_to, validators=[accounts.images.validate_image_file]),
        ),
    ]
