# Generated by Django 5.1.15 on 2026-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(default='ITE Attendance', max_length=80)),
                ('brand_subtitle', models.CharField(default='Department Adviser Portal', max_length=120)),
                ('theme', models.CharField(choices=[('violet', 'Violet'), ('green', 'ITE Green'), ('blue', 'Blue'), ('teal', 'Teal'), ('crimson', 'Crimson'), ('slate', 'Slate')], default='violet', max_length=20)),
                ('color_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('compact_sidebar', models.BooleanField(default=False, help_text='Use a narrower sidebar.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal settings',
                'verbose_name_plural': 'Portal settings',
            },
        ),
    ]
