# Generated by Django 5.1.15 on 2026-06-30 13:47

from django.db import migrations, models


def clear_qrcodes(apps, schema_editor):
    """QR codes are now per-day (not per-slot). Old per-slot rows would violate
    the new ``(student, event, date)`` uniqueness, so drop them — tokens are
    daily and students simply regenerate them."""
    apps.get_model('attendance', 'QRCode').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_options_student_section_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_qrcodes, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-date', 'student'], 'verbose_name': 'QR code'},
        ),
        migrations.AlterUniqueTogether(
            name='qrcode',
            unique_together={('student', 'event', 'date')},
        ),
        migrations.AddField(
            model_name='event',
            name='am_in_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='am_in_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='am_out_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='am_out_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pm_in_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pm_in_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pm_out_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pm_out_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='attendance_type',
        ),
    ]
